// src/app/user/layout.js
import '../globals.css';

export const metadata = {
    title: 'Auth Page',
    description: 'Generated by create next app',
};

export default function AuthLayout({ children }) {
    return (
        <html lang="en">
            <body>
                <main className="w-full">{children}</main>
            </body>
        </html>
    );
}
