import '../globals.css';
import NavigationBarLandingPage from '@/component/NavigationBarLandingPage';
import { BBHSansHegartyRegular, bokor, robotoMono } from '../ui/fonts/font';

export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
    console.log('Rendering RootLayout');
    return (
        <html lang="en">
            <body
                className={` ${robotoMono.variable} ${bokor.variable} ${BBHSansHegartyRegular.variable} antialiased flex justify-center`}
            >
                <NavigationBarLandingPage />
                {children}
            </body>
        </html>
    );
}
