import '../globals.css';
import NavigationBarLandingPage from '@/component/NavigationBarLandingPage';
import { BBHSansHegartyRegular, bokor, robotoMono } from '../ui/fonts/font';
import { auth } from '../../../lib/auth';
import { headers } from 'next/headers';

export const metadata = {
    title: 'Expense and Income Tracker - Landing Page',
    description: 'Generated by create next app',
};

export default async function RootLayout({ children }) {
    const session = await auth.api.getSession({
        headers: await headers(),
    });
    return (
        <html lang="en">
            <body
                className={` ${robotoMono.variable} ${bokor.variable} ${BBHSansHegartyRegular.variable} antialiased flex justify-center`}
            >
                <NavigationBarLandingPage session={session} />
                {children}
            </body>
        </html>
    );
}
