import './globals.css';
import Navigation from '@/component/Navigation';
import { BBHSansHegartyRegular, bokor, robotoMono } from './ui/fonts/font';

export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body
                className={` ${robotoMono.variable} ${bokor.variable} ${BBHSansHegartyRegular.variable} antialiased flex justify-center`}
            >
                <Navigation />
                {children}
            </body>
        </html>
    );
}
