// src/app/user/layout.js
import '../globals.css';
import NavigationBarUserDashboard from '@/component/NavigationBarUserDashboard';
import { BBHSansHegartyRegular, bokor, robotoMono } from '../ui/fonts/font';

export const metadata = {
    title: 'Expense and Income Tracker - User Dashboard',
    description: 'Generated by create next app',
};

export default function UserLayout({ children }) {
    console.log('Rendering UserLayout');

    return (
        <html lang="en">
            <body
                className={`${robotoMono.variable} ${bokor.variable} ${BBHSansHegartyRegular.variable} antialiased flex justify-center`}
            >
                <NavigationBarUserDashboard />
                <main className="w-full">{children}</main>
            </body>
        </html>
    );
}
